/** @format */

export const itemStep2 = [
  "isLogin",
  "password",
  "userName",
  "firstName",
  "lastName",
  "employmentStatus",
  "email",
  "listDataSubmit",
  "questionStep1",
  "skip1",
  "currentLoanStatus",
];

export const itemStep3 = [
  "isLogin",
  "password",
  "userName",
  "firstName",
  "lastName",
  "employmentStatus",
  "email",
  "listDataSubmit",
  "questionStep1",
  "skip1",
  "currentLoanStatus",
  "valueInterestRate",
  "valueInterestRate2",
];

export const itemStep4 = [
  "isLogin",
  "password",
  "userName",
  "firstName",
  "lastName",
  "employmentStatus",
  "email",
  "listDataSubmit",
  "questionStep1",
  "skip1",
  "currentLoanStatus",
  "valueInterestRate",
  "valueInterestRate2",
  "jointApplicationStatus",
];

export const itemStep5 = [
  "isLogin",
  "password",
  "userName",
  "firstName",
  "lastName",
  "employmentStatus",
  "email",
  "listDataSubmit",
  "questionStep1",
  "skip1",
  "currentLoanStatus",
  "valueInterestRate",
  "valueInterestRate2",
  "jointApplicationStatus",
  "firstNameOther",
  "lastNameOther",
];

export const itemStep6 = [
  "isLogin",
  "password",
  "userName",
  "firstName",
  "lastName",
  "employmentStatus",
  "email",
  "listDataSubmit",
  "questionStep1",
  "skip1",
  "currentLoanStatus",
  "valueInterestRate",
  "valueInterestRate2",
  "jointApplicationStatus",
  "firstNameOther",
  "lastNameOther",
  "relationshipYour",
];

export const itemStep7 = [
  "isLogin",
  "password",
  "userName",
  "firstName",
  "lastName",
  "employmentStatus",
  "email",
  "listDataSubmit",
  "questionStep1",
  "skip1",
  "currentLoanStatus",
  "valueInterestRate",
  "valueInterestRate2",
  "jointApplicationStatus",
  "firstNameOther",
  "lastNameOther",
  "relationshipYour",
  "jointApplicantAge",
  "soleApplicantAge",
];
